---
title: "FAO_Draft2"
author: "Linh"
date: "`r Sys.Date()`"
output: html_document
---

Prediciting temperature changes based on agrifood system emissions?

```{r, message=FALSE}
library(tidyverse)
library(plotly)
library(readr)
library(purrr)
```

```{r run:1}
temp <- read_csv("data/Environment_Temperature_change_E_All_Data_(Normalized).csv")
temp$Unit ="Celsius"
temp = temp %>% filter(temp$Element == "Temperature change")
temp = temp %>% filter(`Months Code` == 7020)
#temp <- temp %>% mutate(index = 1:nrow(.))
temp_countryonly = temp %>% filter(`Area Code` < 5000)
```

```{r}
temp_countryonly$Area %>% unique()
sum(is.na(temp_countryonly))
dim(temp_countryonly)
temp 

library(naniar)

vis_miss(temp_countryonly)
temp_countryonly

```


```{r run:2}
# Making a function that removes symbols/letters that are not utf8 compatible such as country names
remove_non_utf8 <- function(vec) {
  vec_cleaned <- iconv(vec, to = "ASCII//IGNORE")
  return(vec_cleaned)
}

world_map = map_data("world")

# Made 2 vectors for the world map names, 1) to check for the exact matching including spaces and another to match similiar letters based on stripped text
world_list = world_map$region %>% unique()
# list 1)
world_oglist = world_list
# list 2)
world_list <- gsub(" ", "", world_list) 
world_list = tolower(world_list)

temp_countryonly$Area_og = temp_countryonly$Area %>% remove_non_utf8()
temp_countryonly$Area = temp_countryonly$Area %>% remove_non_utf8()

country_names = temp_countryonly$Area_og %>% unique()

temp_countryonly$Area = gsub(" ", "", temp_countryonly$Area) 

temp_countryonly$Area = tolower(temp_countryonly$Area)
temp_countryonly$Area = recode(temp_countryonly$Area, 
                               'unitedstatesofamerica' = "usa",
                               'unitedkingdomofgreatbritainandnorthernireland' = 'uk',
                               'republicofkorea' = 'southkorea',
                               "democraticpeople'srepublicofkorea" = "northkorea",
                               "laopeople'sdemocraticrepublic" = 'laos',
                               'runion' = 'reunion',
                               'congo' = 'republicofcongo',
                               'czechia' = 'czechrepublic',
                               'cocos(keeling)islands' = 'cocosislands',
                               'trkiye' = 'turkey')
```

```{r run3}
new_country_names <- rep(NA,(length(temp_countryonly$Area)))
# Loop to find matches and update vector2
for (i in seq_along(new_country_names)) {
  matching_elements <- grepl(world_list[i], temp_countryonly$Area)
  new_country_names[matching_elements] = world_oglist[i]
}

# Loop to find exact matches
for (i in seq_along(new_country_names)) {
  exact_match = intersect(temp_countryonly$Area_og[i], world_oglist)
  if (length(exact_match) > 0) {
    new_country_names[i] = exact_match
  }
}
temp_countryonly$region = new_country_names
temp_countryonly <- temp_countryonly[!is.na(temp_countryonly$region), ]
```

```{r Checking to see any major missing countries and duplicates}
not_in_world <- temp_countryonly$Area_og[!temp_countryonly$Area_og %in% world_map$region]
not_in_world %>% unique()

# Elements present in world_map but not in temp
not_in_temp <- world_map$region[!world_map$region %in% temp_countryonly$region]
not_in_temp %>% unique()

#Checking for duplicates
duplicates <- duplicated(temp_countryonly) | duplicated(temp_countryonly, fromLast = TRUE)
# Subset the data frame to show rows with duplicates
df_with_duplicates <- temp_countryonly[duplicates, ]
```



```{r run:4}
world_map = map_data("world")
temp = temp_countryonly %>% select("region", "Year", "Value") 
#Removing duplicates by taking the average values
temp <- temp %>%
  group_by(region, Year) %>%
  summarize(Value = mean(Value, na.rm = TRUE))


temp_2009 = temp %>% filter(Year == 2009)

limit <- max(abs(temp_2009$Value), na.rm = TRUE) * c(-1, 1)


leftjoin_temp2009 = left_join(world_map,temp_2009)

p = ggplot(leftjoin_temp2009, aes(x =long, y=lat, group = group, fill = Value)) + geom_polygon(color = "white", size = 0.1) +theme_bw() + scale_fill_distiller(type = "div", limit = limit)  + coord_fixed(1.3) + labs(x= "Latitude", y="Longitude")
p
ggplotly(p)

```



```{r warning=FALSE}
setwd('/Users/linh/Documents/Github/FAO-dataset-analysis/data/emissions')
emissions_files = list.files(pattern="*.csv")
emissions = lapply(emissions_files, read.csv)
```

```{r}
library(stringr)
name_emissions = c()
for (i in 1:length(emissions_files)) {
  emssion = emissions_files[i]
  underscore_positions <- str_locate_all(emssion, "_")[[1]]
  name <- substr(emssion, start = 1, stop = underscore_positions[4, "start"] - 1)
  name_emissions = name_emissions %>% c(name)
  
}

names(emissions) <- name_emissions
```

```{r}

unique_list = list()
for (i in 1:length(emissions)){
  emission = emissions[[i]] %>% select(c(Area, Element, Year, Unit, Value))
  emission$Unit <- sub("kt", "kilotonnes", emission$Unit)
  unique_emission = emission$Element %>% unique() %>% unlist()
  unique_list = unique_list %>% c(unique_emission)
  emissions[[i]] = emission
  }

unique_list %>% unlist() %>% unique()
```


```{r, echo = FALSE}
library(tidyverse)
unique_list = list()
for (i in 1:length(emissions)){
  emission = emissions[[i]] %>% select(c(Area, Element, Year, Unit, Value))
  emission$Unit <- sub("kt", "kilotonnes", emission$Unit)
  emission = emission %>% filter(Unit == "kilotonnes")
  unique_emission = emission$Element %>% unique() %>% unlist()
  unique_list = unique_list %>% c(unique_emission)
  emissions[[i]] = emission
  }


```

```{r}
unique_list %>% unlist() %>% unique()
```



```{r}
#viewing all unique eleements and how they were measured
df = data.frame(name = c(NA), emissions_w_units = c(NA))

for (i in 1:length(emissions)){
  name = name_emissions[i]
  unique_elements_units = emissions[[i]] %>% select(Element, Unit) %>% unique()
  elem_unit = paste(unique_elements_units$Element, unique_elements_units$Unit, sep = ", ")
  df = df %>% rbind(c(name, elem_unit))
  
  }

df = df%>%drop_na()
```


```{r}
a=emissions$Emissions_Agriculture_Burning_crop$Element %>% unique() %>% str_c(collapse = ", ")


dupls = duplicated(emissions$Emissions_Agriculture_Burning_crop$Element) | duplicated(emissions$Emissions_Agriculture_Burning_crop$Unit) 
```

```{r}
b = emissions$Emissions_Agriculture_Burning_crop %>% select(Element, Unit) %>% unique() 
b = paste(b$Element, b$Unit, sep = ", ")

b = b %>% as.list()
b
```




